import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {ThemeProvider} from "@/components/theme-provider"
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//providers wrap around our application and give them access to data
//NextThemesProvider - give our application access to light / dark mode data
// providers are generrally on the client side ("use client")

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme="dark">
        <main className="flex min-h-screen flex-col items-center lg:p-24 md:p-12">
          <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
            <Link href="/">
              <h2 className="text-2x1 text-bold">Pokemon Finder</h2>
            </Link>
            
          </div>
          {children}
        </main>
        </ThemeProvider>
        </body>
    </html>
  )
}
